spring:
  application:
     name : CONFIG-DEFAULT

#eureka client config
eureka:
   prefer-ip-address: true
  client:
    fetch-registry: true 
    service-url:
      defalutZone : http://localhost:8761/eureka
      # now wel will use this url to register to the server
      
